url: https://therrick.github.io
#baseurl: /

# Site settings
title: Key Square, Inc.
email: webcontacts
domain: key-square.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1B7200
  secondary: 00c800  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Hunter Ware
  pic: 1
  link:
    type: linkedin
    url: https://www.linkedin.com/pub/hunter-ware/7/595/663

- name: Bill Tompkins
  pic: 2
  link:
    type: linkedin
    url: https://www.linkedin.com/pub/bill-tompkins/9/689/40a

- name: Jonathan Tillack
  pic: 3
  link:
    type: linkedin
    url: https://www.linkedin.com/pub/jonathan-tillack/6/a22/962

- name: Tom Herrick
  pic: 4
  link:
    type: linkedin
    url: https://www.linkedin.com/in/therrick

- name: Bill Davis
  pic: 5
  link:
    type: linkedin
    url: https://www.linkedin.com/pub/bill-davis/46/54a/5a2

- name: Adam Showalter
  pic: 6
  link:
    type: linkedin
    url: https://www.linkedin.com/in/adamshowalter

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
- line: Key Square, Inc.
- line: 609 East Market St.
- line: Suite 206
- line: Charlottesville, VA 22902

phone: +1.434.218.2322

# Build settings
markdown: kramdown
permalink: pretty