url: http://www.key-square.com
#baseurl: /

# Site settings
title: Key Square, Inc.
email: webcontacts
domain: key-square.com
description: "Key Square is an engineering services company offering a wide range of custom software and hardware development services including device design, analog and digital circuit design, schematic capture, layout, and manufacturing advisory services. We also offer a full range of software services including application and algorithm development, embedded programming, and server-side software design and development."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1B7200
  secondary: 00c800  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Hunter Ware
  pic: 1
  link:
    type: linkedin
    url: https://www.linkedin.com/pub/hunter-ware/7/595/663

- name: Bill Tompkins
  pic: 2
  link:
    type: linkedin
    url: https://www.linkedin.com/pub/bill-tompkins/9/689/40a

- name: Tom Herrick
  pic: 4
  link:
    type: linkedin
    url: https://www.linkedin.com/in/therrick

- name: Adam Showalter
  pic: 5
  link:
    type: linkedin
    url: https://www.linkedin.com/in/adamshowalter

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
- line: Key Square, Inc.
- line: 977 Seminole Trail #282
- line: Charlottesville, VA 22901

phone: +1.434.218.2322

# Build settings
markdown: kramdown
permalink: pretty
